services:
  masterdb:
    container_name: RetailMasterDB
    build: .
    ports:
      - "3306:3306"
    volumes:
      - ./init-db:/init-db
      - ./scripts:/scripts
      - ./data:/var/lib/mysql
    entrypoint: ["/bin/bash", "/scripts/init.sh"]
    restart: unless-stopped
    stdin_open: true
    tty: true